### ISSUE TITLE
Cargo add fails

### ISSUE THREAD

**Issue by alper** [ptal/pcp#29]
When I add the package I get:
```
error: no matching package named `quickersort` found
location searched: registry `crates-io`
required by package `pcp v0.2.0`
```

**Comment by alper** [comment]
Which is weird because checking out and building the project works.

**Comment by alper** [comment]
Never mind. I'm doing: `cargo add libpcp` and that works.

**Comment by ptal** [comment]
Not sure what was going on but in the first message you sent "required by package `pcp v0.2.0`", the version of pcp was outdated so maybe cargo needed a refresh or something.
